baseurl  = "https://psuvtk.github.io/"
languageCode = "zh-cn"

title = "技术的细节"

theme = "cactus"

publishDir = "./docs"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[params]
  description = "愚昧山峰, 刻意练习"
  author = "Kristoffer.Song"
