baseurl  = "https://psuvtk.github.io/"
languageCode = "zh-cn"

title = "Early is on Time"

theme = "cactus"

publishDir = "./docs"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2


[[menu.main]]
name = "生活"
url = "/life"
weight = 2

[[menu.main]]
name = "面经"
url = "/algo"
weight = 3

[[menu.main]]
name = "本人"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[params]
  description = ""
  author = "Kristoffer.Song"

  colortheme = "classic" # dark, light, white, or classic


  showAllPostsOnHomePage = true
  postsOnHomePage = 15

  tagsOverview = true
  tocInline = true