baseurl  = "https://psuvtk.github.io/"
languageCode = "zh-cn"

title = "Early is on timeASD"

theme = "cactus"

publishDir = "./docs"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2


[[menu.main]]
name = "Life"
url = "/life"
weight = 2


[[menu.main]]
name = "About Me"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[params]
  description = ""
  author = "Kristoffer.Song"

  colortheme = "classic" # dark, light, white, or classic


  showAllPostsOnHomePage = true
  postsOnHomePage = 15

  tagsOverview = true
  tocInline = true